//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieID { get; set; }
        public string Name { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Category { get; set; }
        public string Language { get; set; }
        public Nullable<int> NumbeInStock { get; set; }
    }
}
